### ISSUE TITLE
[ Request ] Add Playwright Testing

### ISSUE THREAD

**Issue by HananoshikaYomaru** [dev-xo/remix-saas#239]
refer to : 

1. https://github.com/sergiodxa/remix-auth/blob/main/test/authorizers.test.ts 
2. https://github.com/sergiodxa/remix-auth/discussions/166

**Comment by dev-xo** [comment]
Hello @HananoshikaYomaru, would appreciate if you can expand on your opened issue.

I guess your intention is for Remix SaaS to add Playwright tests?
- To test authentication?

As you can see, there are a few questions that could be made more clear if you would expand on your issue.

Thanks.

**Comment by HananoshikaYomaru** [comment]
it is not to test the authentication library. it is to test my system authentication is done correctly. For example I want to test the login flow using playwright ui mode. I also want to test features that require authentication and make sure auth protection are working now and in the future (regression testing), in case of me accidentially remove the auth or do some stupid thing etc.

**Comment by dev-xo** [comment]
It's hard to know what you're looking for without a proper explanation of the issue, @HananoshikaYomaru.

Please take your time to explain exactly what you're looking for. For example:
- It would be great to add Playwright Testing because...
- My use case for it would be...

We can't understand the issue without a proper explanation. You're also referencing two links that don't explain your current issue but instead show some examples.

We'll probably end up closing this.
