### ISSUE TITLE
[ Question ] Where would you add Apps/Services (monorepo)?

### ISSUE THREAD

**Issue by henrikwirth** [dev-xo/remix-saas#269]
Hi there, I am new to Remix and stumbled upon this awesome template. Looks like a really good starter for my use-case, thanks for all the work.

**I was wondering about a few things:**
- If one would build services/apps now that should only be available for certain subscriptions, where would you create these and how would you scaffold it?
- Would it make sense to create a monorepo to separate packages and apps with their dependencies?
- Would be interesting to have an example service in this template to guide a new user/developer or give some suggestions in the docs to do so.

**Comment by dev-xo** [comment]
Hello @henrikwirth.

The idea with this template is to keep it as simple and easy to handle and start for everyone. We left out a few services and some other features for this same reason.

Not an expert with monorepos here, so probably I will not be able to help with that, sadly. Wonder if you can either ask this question in the Remix Discord `#random` channel and keep it general, not aimed at any project/template in particular, or in some other forum or place.
- ChatGPT or some AI could help you a bit?

> Would it make sense to create a monorepo to separate packages and apps with their dependencies?
- I guess it would make sense, sadly no idea how you could handle that in order to also access subscriptions.

> Would be interesting to have an example service in this template to guide a new user/developer or give some suggestions in the docs to do so.
- I'm okay with adding documentation that could be related to how to handle monorepos in order to have subscriptions available for all the apps. So if you find something that could help and want to contribute to that, let me know!

So yeah, I will leave this issue open for a bit, in case you can find or come up with something related. I usually try to avoid monorepos if not needed, although probably if you want to share subscriptions across multiple apps, it sounds like a monorepo job for sure.
