### ISSUE TITLE
[ Question ] Production Use

### ISSUE THREAD

**Issue by aaronksaunders** [dev-xo/remix-saas#304]
this looks pretty awesome and thanks for putting all this together. 

this is more of a question than an actual issue; DO you know of anyone that is using this as a starting point for something that is running in a production environment site will real world usage, transactions and traffic?

Thanks in advance

**Comment by dev-xo** [comment]
Hello @aaronksaunders, not sure to say yet. I know of a few people who are using the template or stripped down only the parts they needed (like the Stripe implementation), but I'm not sure if anyone went into production with it yet.

In the end, the "production" phase is subjective to the needs you may have. For example, if you only need the Stripe implementation in order to set your app on top of it, that would be more than enough to be production-ready!
