### ISSUE TITLE
[ Question ] Stripe Products Seeding

### ISSUE THREAD

**Issue by marsch** [dev-xo/remix-saas#356]
so when you do: 

```
npx prisma migrate dev --name init 
```

it always skipping with `🏃‍♂️ Skipping Stripe products creation and seeding.`

not sure if this intended, will file a PR for this

**Comment by dev-xo** [comment]
Hello @marsch.

As far as I remember, that's intended, as it has a custom message for it. Ideally, we want to do one of the following things before migrating/re-seeding:
- **Clean up our Stripe data** (including plans).
- **Delete our database plans and seed those again with the available Stripe data** (plans).

As the project is still part of a previous code, the first option was selected. In order to properly do migrations again, we will need to clean our Stripe data, as new plans will be created and stored in our database.

Nowadays, I personally follow the second approach:
- Stripe plans are not being re-created; rather, we clean up our Stripe database plans and seed those again with the available Stripe data (plans).

So yeah, in the current code, we are taking the first approach, which requires clean Stripe data in order to properly run the migrations. That's also specified in the docs.

- - -

With that said, I have in mind to come up with a new version of Remix SaaS, and the second approach will be the main one, as it simplifies the seeding/migration process a lot.
